### PR TITLE
feat(outDir) support outdir

### PR DESCRIPTION
**Pull request by basarat**
The rest just works :rose:

### CODE REVIEW

**Comment by kitsonk** [comment]
@basarat I was unable to find a CLA under your GitHub username as part of the Dojo Foundation.  We require CLAs for any contributions.  Could you take a moment to [file a CLA](http://dojofoundation.org/about/cla) or let me know what username or e-mail it is filed under?

**Comment by basarat** [comment]
CLA Filed

**Comment by kitsonk** [comment]
Basarat Syed submitted a CLA on 2015-09-03 23:53:53.

**Comment by kitsonk** [comment]
Merged via a42f05ef9d96232c27aa169e49e82fb86d767738

**Pull request closed without merging**
