### PR TITLE
Add support for rootDir option in tsconfig

### PR DESCRIPTION
**Pull request by richtea**
When the `tsconfig.json` file specifies a `rootDir`, this should also affect the generated id of the modules. 

Currently, if you have a source file called `src/index.ts` and your tsconfig is in the root directory, the generated module id will be `myname/src/index`. This is appropriate if your output file is called `dist/src/index.js`; but if you have used the `rootDir: 'src'` option in the tsconfig then you probably want your generated module id to be `myname/index`.

### CODE REVIEW

**Comment by kitsonk** [comment]
@richtea we require CLAs for any contributions as part of the Dojo Foundation.  I was unable to find a CLA based on your GitHub username.  Could you please take a moment to [file a CLA](http://dojofoundation.org/about/cla) or let me know what username or e-mail address you used?

**Comment by richtea** [comment]
Hi

I've completed the CLA under this email address. Please let me know if there is anything else you need from me. 

Thanks
Rich

**Comment by richtea** [comment]
Apologies, the CLA is filed under rich -at- tebb.me.uk

**Comment by kitsonk** [comment]
> Rich Tebb submitted a CLA on 2015-12-11 21:10:07.

**Pull request closed without merging**
