### PR TITLE
added the option to skip ".d.ts" files

### PR DESCRIPTION
**Pull request by alex20465**
In some cases, the external declarations shouldn't be present inside the module declarations, so i added the option <code>skipDeclarations</code>, which skips the write-process when the filename ends with: <code>.d.ts</code>.

### CODE REVIEW

**Comment by kitsonk** [comment]
Why would the [options.exclude](https://github.com/SitePen/dts-generator/blob/16a86fc3cb3e06c8ebdf7884a9f4c4542101fe60/index.ts#L172) not meet this requirement?

**Comment by alex20465** [comment]
never mind, i thought the <code>exclude</code> option was for the compile-phase.

**Comment by dgoldstein0** [comment]
perhaps this should be closed out?

**Comment by dylans** [comment]
Closing out given earlier comments. If there's still a need, please rebase and open a new PR. Thanks!

**Pull request closed without merging**
