### PR TITLE
upgrade typescript

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by kitsonk** [comment]
The `peerDependency` of `"typescript": "^1.6.0"` covers the current version of TypeScript so there is no need to change this.  Also this PR changes the whitespace from tabs to spaces.  We should preserve the whitespace (even though npm doesn't respect whitespace).

Why are you trying to change the compiler options?  I would prefer to see what issue it is causing and why being explicit about so many options is necessary.  It could be beneficial to take the project's options and merge the ones we care about, but this PR does not reflect that.

**Comment by taoqf** [comment]
i did that because there were error when i run npm install

**Comment by kitsonk** [comment]
> i did that because there were error when i run npm install

What error?

**Comment by taoqf** [comment]
i hava a gulpfile.js like this:
```
var gulp = require('gulp');
var packageJson = require('./package.json');
var tsconfig = require('./tsconfig.json');

gulp.task('default', function() {
	require('dts-generator').default({
		name: packageJson.name,
		// project: './',
		baseDir: './src',
		// externs: ['dojo-core/interfaces', 'express', 'nools'],
		out: './dist/typings/' + packageJson.name + '-' + packageJson.version + '.d.ts',
		src: ['./src/**/*.ts', './typings/**/*.d.ts']
	});
});
```
i got this when i run 'gulp':
```
[10:25:03] Starting 'default'...
[10:25:03] Finished 'default' after 121 ms
Unhandled rejection SyntaxError: Unable to resolve configuration.
    at /home/taoqf/git/feidao-web/js-src/node_modules/dts-generator/index.js:138:24
    at Promise._execute (/home/taoqf/git/feidao-web/js-src/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/taoqf/git/feidao-web/js-src/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/taoqf/git/feidao-web/js-src/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.generate [as default] (/home/taoqf/git/feidao-web/js-src/node_modules/dts-generator/index.js:137:20)
    at Gulp.<anonymous> (/home/taoqf/git/feidao-web/js-src/gulpfile.js:6:34)
    at module.exports (/home/taoqf/git/feidao-web/js-src/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/taoqf/git/feidao-web/js-src/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/taoqf/git/feidao-web/js-src/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/taoqf/git/feidao-web/js-src/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by taoqf** [comment]
npm install:
```
npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> intern@3.0.6 install /home/taoqf/github/dts-generator/node_modules/intern
> node support/fixdeps.js


> dts-generator@1.8.0-pre prepublish /home/taoqf/github/dts-generator
> tsc --module commonjs --target es5 typings/tsd.d.ts index.ts bin/dts-generator.ts

index.ts(7,21): error TS2307: Cannot find module 'typescript'.

npm WARN dts-generator@1.8.0-pre requires a peer of typescript@^1.6.0 but none was installed.
npm WARN tslint@3.5.0 requires a peer of typescript@>=1.7.3 but none was installed.
npm ERR! Linux 4.5.0-3-default
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! dts-generator@1.8.0-pre prepublish: `tsc --module commonjs --target es5 typings/tsd.d.ts index.ts bin/dts-generator.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the dts-generator@1.8.0-pre prepublish script 'tsc --module commonjs --target es5 typings/tsd.d.ts index.ts bin/dts-generator.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dts-generator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --module commonjs --target es5 typings/tsd.d.ts index.ts bin/dts-generator.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dts-generator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dts-generator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/taoqf/github/dts-generator/npm-debug.log

```

**Comment by kitsonk** [comment]
npm3 [does not install peer dependencies automatically](http://blog.npmjs.org/post/110924823920/npm-weekly-5).

The npm warning is indicating this:

```
npm WARN dts-generator@1.8.0-pre requires a peer of typescript@^1.6.0 but none was installed.
npm WARN tslint@3.5.0 requires a peer of typescript@>=1.7.3 but none was installed.
```

In order to resolve this, you need to install TypeScript in this package.

```
$ npm install typescript
```

You can also specify a particular version if you wish:

```
$ npm install typescript@1.8.10
```

Version `1.8.10` would satisfy both the errors mentioned by npm, `dts-generator` requires `^1.6.0` and `tslint` requires `>=1.7.3`.

**Pull request closed without merging**
