### PR TITLE
Handle ES6 main module declaration

### LINKED ISSUE #19: alternate to current `main` parameter's syntax
I'd like you to implement an option for an alternate to the current syntax generated for the `main` parameter.  This is what I would like it to look like:

```javascript
declare module 'aurelia-metadata' {
	export * from 'aurelia-metadata/index';
}
```

If you were to do that (and with the more complete fix [here](https://github.com/SitePen/dts-generator/commit/d4717fa65988be2cb3359ac0167d89785561f610)), i will be able to automatically generate the [Aurelia](http://aurelia.io) type definition files.

here's the code i use at the end of the `generate` function to output the above syntax:

```javascript
        if (options.main) {
            output.write(("declare module '" + options.name + "' {") + eol + indent);
            output.write(("export * from '" + options.main + "';") + eol);
            output.write('}' + eol);
            sendMessage("Aliased main module " + options.name + " to " + options.main);
        }
```

### PR DESCRIPTION
**Pull request by mtraynham**
Fixes #19, resolves #25 

Doesn't emit if the "main" module has no export declarations or assignment.  In the ES6 case, it can emit the declaration or assignment pattern based on the export kinds from the main module.

### CODE REVIEW

**Comment by kitsonk** [comment]
@mtraynham I was unable to find a CLA on file for you as part of the Dojo Foundation.  We require CLAs for any contributions.  Could you take a moment and [file a CLA](http://dojofoundation.org/about/cla) or let me know what username or e-mail it is filed under?

**Comment by mtraynham** [comment]
@kitsonk Signed with skitch920@gmail.com

**Comment by kitsonk** [comment]
Matthew Traynham submitted a CLA on 2015-09-03 23:14:07.

**Comment by mtraynham** [comment]
@kitsonk What's the status on getting this accepted?

**Comment by kitsonk** [comment]
Apologies... I got hung up on support `tsconfig.json` for the next release, but I will take a look at this later today.

**Comment by mtraynham** [comment]
Thanks!

**Comment by speigg** [comment]
:+1:

**Comment by stephenlautier** [comment]
bump! :+1:

**Comment by stephenlautier** [comment]
Is there a plan when this will be released?

**Comment by davidbonnici1984** [comment]
It would be great if this pull request is merged :)

**Comment by dylans** [comment]
Sorry for the delays, we will review and land this by the end of the week. We'll also plan to tag an updated release in the next week or so.

**Pull request closed without merging**
